### PR TITLE
Credit.mp4

### PR DESCRIPTION
**Pull request by Vilagamer999**
;)

### CODE REVIEW

**Comment by Vilagamer999** [comment]
Approve

**Comment by vincentdistoer3** [comment]
request changes

**Review by vincentdistoer3 — DISMISSED** [review]
Changes requested.

**Comment by vincentdistoer3** [comment]
please add pepper and bobolob too
@ZestyPepper 
@Bobolob54321

**Comment by Vilagamer999** [comment]
Ok

**Comment by Vilagamer999** [comment]
Done

**Review by Minion3665 — APPROVED** [review]
looks good

**Pull request merged**
