### PR TITLE
Added apple iOS support ;)

### PR DESCRIPTION
**Pull request by Vilagamer999**
Approve

### CODE REVIEW

**Comment by Minion3665** [comment]
approve

**Review by Minion3665 — APPROVED** [review]

**Comment by Minion3665** [comment]
can you do the manifest next for android web apps (and also ios)
@Vilagamer999 @chromebot-websites/beta

**Comment by Vilagamer999** [comment]
Approve

**Comment by Minion3665** [comment]
merging when green

**Pull request merged**
