### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vilagamer999**

### CODE REVIEW

**Comment by Vilagamer999** [comment]
F no

**Comment by Minion3665** [comment]
approve

**Review by Minion3665 — APPROVED** [review]

**Comment by Vilagamer999** [comment]
Rip, pull approve beeing stupid

**Comment by Vilagamer999** [comment]
Approve

**Comment by Vilagamer999** [comment]
approve

**Comment by Vilagamer999** [comment]
F

**Pull request merged**
