### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vilagamer999**

### CODE REVIEW

**Comment by Vilagamer999** [comment]
Hey @Minion3665 is this creative common good?
https://creativecommons.org/licenses/by-nd/4.0/

**Comment by Vilagamer999** [comment]
Also please turn off do not disturb... @Minion3665

**Comment by Minion3665** [comment]
@Vilagamer999 creative commons is fine. I have DND on for a reason. I would prefer gnugpl3 though

**Comment by Minion3665** [comment]
actually just go with gnugpl 3

**Comment by Minion3665** [comment]
not creative commons

**Comment by Minion3665** [comment]
actually no

**Comment by Minion3665** [comment]
use the creative commons

**Comment by Minion3665** [comment]
I like the no derivative clause

**Comment by Vilagamer999** [comment]
Bruh

**Pull request closed without merging**
