### PR TITLE
Backbutton hijack ;)

### PR DESCRIPTION
**Pull request by Vilagamer999**
Lel

### CODE REVIEW

**Comment by Vilagamer999** [comment]
Approve

**Comment by Minion3665** [comment]
request changes
I don't want to be an ahole I have decided. Sorry lluc

**Comment by Minion3665** [comment]
request changes

**Review by Minion3665 — CHANGES_REQUESTED** [review]
Changes requested.

**Comment by Minion3665** [comment]
decline and close

**Pull request closed without merging**
