### PR TITLE
Update features.js

### PR DESCRIPTION
**Pull request by Vilagamer999**

### CODE REVIEW

**Comment by Minion3665** [comment]
request changes

**Review by Minion3665 — CHANGES_REQUESTED** [review]
Changes requested.

**Comment by Minion3665** [comment]
please don't add this to the feature page

**Comment by Minion3665** [comment]
also shouldn't be high pri

**Comment by Minion3665** [comment]
thinking of adding sentry too- what d' you think

**Comment by Minion3665** [comment]
also- what's the pull-approve priority level thing about. I didn't set that up

**Comment by Vilagamer999** [comment]
what changes do you want me to do?

**Comment by Minion3665** [comment]
close & lock

**Pull request closed without merging**
