### PR TITLE
Create .pullapprove.yml

### PR DESCRIPTION
**Pull request by Minion3665**
- [x] add pullapprove config

### CODE REVIEW

**Review by Minion3665 — COMMENTED** [review]
/pullapprove-test
version: 3

pullapprove_conditions:
- "base.ref == 'master'"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Tests must pass before review starts"
- condition: "'wip' in labels"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  protected:
    conditions:
    - >
    # Block editing markdown, html, yaml, or json files
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
    # Block editing core configuration files
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
    # Block editing the logos
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
request_order: given

**Review by Minion3665 — COMMENTED** [review]
/pullapprove-test
version: 3

pullapprove_conditions:
- "base.ref == 'master'"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Tests must pass before review starts"
- condition: "'wip' in labels"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  protected:
    conditions:
    - >
      # Block editing markdown, html, yaml, or json files
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      # Block editing core configuration files
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      # Block editing the logos
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
request_order: given

**Review by Minion3665 — COMMENTED** [review]
/pullapprove-test
version: 3

pullapprove_conditions:
- "base.ref == 'master'"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Tests must pass before review starts"
- condition: "'wip' in labels"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
request_order: given

**Review by Minion3665 — COMMENTED** [review]
/pullapprove-test
```yml
version: 3

pullapprove_conditions:
- "base.ref == 'master'"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Tests must pass before review starts"
- condition: "'wip' in labels"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
request_order: given
```

**Review by Minion3665 — COMMENTED** [review]
/pullapprove-test
```yml
version: 3

pullapprove_conditions:
- "base.ref == 'master'"
- condition: "'*travis*' in statuses.successful"
  unmet_status: "failure"
  explanation: "Tests must pass before review starts"
- condition: "'wip' in labels"
  unmet_status: pending
  explanation: "Work in progress"

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    reviewers:
      users:
      - Minion3665
    reviews:
      required: 1
      request: 1
```

**Comment by vincentdistoer3** [comment]
Approve

**Review by vincentdistoer3 — APPROVED** [review]

**Pull request merged**
