### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vilagamer999**

### CODE REVIEW

**Comment by Minion3665** [comment]
request changes

**Review by Minion3665 — CHANGES_REQUESTED** [review]
Changes requested.

**Comment by Minion3665** [comment]
Please update it so that it doesn't change the 'who made this'

**Comment by Vilagamer999** [comment]
I updated it

**Comment by Minion3665** [comment]
request changes

**Review by Minion3665 — CHANGES_REQUESTED** [review]
Changes requested.

**Comment by Minion3665** [comment]
there are still references to https://chromebot.cf
> If the build is passing that means that the latest and greatest is on https://chromebot.cf, if not then maybe try fixing and create a pull request (or just commit directly to the master branch (pontentially unsafe) - don't worry, the site won't break; it just won't have the latest commits.

**Comment by Vilagamer999** [comment]
approve

**Comment by Minion3665** [comment]
approve

**Review by Minion3665 — APPROVED** [review]

**Pull request merged**
